const KEY = 'bakers_diary_offline_v1';
const now = () => new Date().toISOString();
const id = (prefix) => `${prefix}_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;

const demoRecipes = [
  { id: 'demo_babka', title: 'Chocolate Babka', description: 'Rich chocolate-swirled yeasted bread, twisted and braided before its second rise.', category: 'Bread', yield: '1 loaf', servings: 12, prepTimeMin: 45, cookTimeMin: 35, favorite: true, status: 'published', ingredients: [
    ['All-purpose flour',500,'g'],['Whole milk',180,'ml'],['Butter',100,'g'],['Dark chocolate',200,'g','chopped'],['Eggs',2,'piece'],['Sugar',90,'g'],['Active dry yeast',7,'g']
  ].map((x,i)=>({id:`babka_i${i}`,name:x[0],quantity:x[1],unit:x[2],note:x[3]||null,order:i+1})), steps: [
    ['Make the dough: combine flour, milk, eggs, sugar, and yeast. Knead until smooth.',null],['Knead the dough for 10 minutes until elastic.',600],['First rise: cover and let rise until doubled.',5400],['Roll the dough into a large rectangle and spread the chocolate filling evenly.',null],['Twist and braid the filled dough into a loaf shape.',null],['Second rise: cover and let rise until puffy.',3600],['Bake at 180°C until deep golden brown.',2100],['Cool completely, then glaze.',1800]
  ].map((x,i)=>({id:`babka_s${i}`,instruction:x[0],timerSeconds:x[1],order:i+1})), createdAt: now(), updatedAt: now(), coverImage: null },
  { id: 'demo_croissants', title: 'Classic Croissants', description: 'Laminated butter dough, folded and shaped into the classic crescent.', category: 'Pastry', yield: '8 croissants', servings: 8, prepTimeMin: 90, cookTimeMin: 20, favorite: false, status: 'published', ingredients: [['Bread flour',500,'g'],['Butter',280,'g','for laminating'],['Whole milk',120,'ml'],['Sugar',55,'g'],['Active dry yeast',11,'g']].map((x,i)=>({id:`cro_i${i}`,name:x[0],quantity:x[1],unit:x[2],note:x[3]||null,order:i+1})), steps: [['Make the détrempe (base dough) and chill.',3600],['Laminate: fold in the butter block in three turns, chilling between each.',null],['Roll out and cut into triangles.',null],['Shape into crescents and proof until jiggly.',7200],['Egg wash and bake until deep golden.',1200]].map((x,i)=>({id:`cro_s${i}`,instruction:x[0],timerSeconds:x[1],order:i+1})), createdAt: now(), updatedAt: now(), coverImage: null },
  { id: 'demo_sourdough', title: 'Sourdough Country Loaf', description: 'Naturally leavened, long fermented, baked in a Dutch oven.', category: 'Bread', yield: '1 loaf', servings: 14, prepTimeMin: 30, cookTimeMin: 45, favorite: false, status: 'published', ingredients: [['Bread flour',450,'g'],['Whole wheat flour',50,'g'],['Water',375,'ml'],['Active sourdough starter',100,'g'],['Salt',10,'g']].map((x,i)=>({id:`sour_i${i}`,name:x[0],quantity:x[1],unit:x[2],order:i+1})), steps: [['Mix flour and water, autolyse 30 minutes.',1800],['Add starter and salt, mix thoroughly.',null],['Bulk ferment with periodic folds.',14400],['Shape and cold proof overnight.',null],['Bake covered, then uncovered, in a Dutch oven.',2700]].map((x,i)=>({id:`sour_s${i}`,instruction:x[0],timerSeconds:x[1],order:i+1})), createdAt: now(), updatedAt: now(), coverImage: null },
  { id: 'demo_cake', title: 'Lemon Blueberry Cake', description: 'Bright, tender crumb cake studded with fresh blueberries.', category: 'Cake', yield: '1 cake', servings: 10, prepTimeMin: 25, cookTimeMin: 50, favorite: false, status: 'published', ingredients: [['All-purpose flour',300,'g'],['Butter',170,'g'],['Sugar',220,'g'],['Eggs',3,'piece'],['Blueberries',200,'g','fresh'],['Lemon',1,'piece','zested and juiced']].map((x,i)=>({id:`cake_i${i}`,name:x[0],quantity:x[1],unit:x[2],note:x[3]||null,order:i+1})), steps: [['Cream butter and sugar until pale and fluffy.',300],['Beat in eggs one at a time, then fold in lemon zest and juice.',null],['Fold in flour, then blueberries.',null],['Bake at 175°C until a skewer comes out clean.',3000]].map((x,i)=>({id:`cake_s${i}`,instruction:x[0],timerSeconds:x[1],order:i+1})), createdAt: now(), updatedAt: now(), coverImage: null }
];

function seed() {
  return { user: { id:'local_user', displayName:'Chef Kats' }, settings:{ id:'local_settings', userId:'local_user', theme:'night', showDedicationOnLogin:true }, recipes: demoRecipes, sessions: [], groceries: [], media: [] };
}
function load() { try { return JSON.parse(localStorage.getItem(KEY)) || seed(); } catch { return seed(); } }
function save(db) { localStorage.setItem(KEY, JSON.stringify(db)); return db; }
const clone = (x) => JSON.parse(JSON.stringify(x));
function recipeWithMedia(db, recipe) { if (!recipe) return null; return { ...recipe, coverImage: db.media.find(m=>m.id===recipe.coverImageId) || recipe.coverImage || null }; }
function sessionFull(db, s) { if (!s) return null; const recipe = db.recipes.find(r=>r.id===s.recipeId); return { ...s, recipe: recipe ? { id:recipe.id,title:recipe.title,coverImage:recipeWithMedia(db,recipe).coverImage } : null, finalPhoto:db.media.find(m=>m.id===s.finalPhotoId)||null, steps:s.steps.map(ss=>({ ...ss, recipeStep:recipe?.steps.find(rs=>rs.id===ss.recipeStepId)||null, photos:(ss.photoIds||[]).map(pid=>db.media.find(m=>m.id===pid)).filter(Boolean) })) }; }

export const offline = {
  login: async () => ({ token:'offline-device', user:load().user }), getMe:async()=>({success:true,user:load().user}), forgotPassword:async()=>({success:true,message:'This offline edition uses trusted single-device access.'}),
  getSettings:async()=>({success:true,settings:clone(load().settings)}), updateSettings:async(body)=>{const db=load();db.settings={...db.settings,...body};save(db);return{success:true,settings:clone(db.settings)}},
  getRecipes:async(params='')=>{const db=load();const q=new URLSearchParams(params.replace(/^\?/,''));let recipes=db.recipes;if(q.get('favorite')==='true')recipes=recipes.filter(r=>r.favorite);if(q.get('status'))recipes=recipes.filter(r=>r.status===q.get('status'));recipes=[...recipes].sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt))).map(r=>recipeWithMedia(db,r));return{success:true,count:recipes.length,recipes:clone(recipes)}},
  getRecipe:async(rid)=>{const db=load();const recipe=recipeWithMedia(db,db.recipes.find(r=>r.id===rid));if(!recipe)throw new Error('Recipe not found');return{success:true,recipe:clone(recipe)}},
  createRecipe:async(body)=>{const db=load();const rid=id('recipe');const recipe={...body,id:rid,favorite:false,status:body.status==='published'?'published':'draft',coverImageId:body.coverImageId||null,ingredients:(body.ingredients||[]).map((x,i)=>({...x,id:id('ingredient'),quantity:Number(x.quantity),order:x.order??i})),steps:(body.steps||[]).map((x,i)=>({...x,id:id('step'),order:x.order??i,timerSeconds:x.timerSeconds?Number(x.timerSeconds):null})),createdAt:now(),updatedAt:now()};db.recipes.push(recipe);save(db);return{success:true,recipe:clone(recipeWithMedia(db,recipe))}},
  updateRecipe:async(rid,body)=>{const db=load();const idx=db.recipes.findIndex(r=>r.id===rid);if(idx<0)throw new Error('Recipe not found');const historical=db.sessions.some(s=>s.recipeId===rid);if(historical&&body.steps&&body.steps.length!==db.recipes[idx].steps.length)throw new Error('This recipe has bake history. Existing Method steps may be edited, but steps cannot be added or removed.');const current=db.recipes[idx];const next={...current,...body,updatedAt:now()};if(body.ingredients)next.ingredients=body.ingredients.map((x,i)=>({...x,id:x.id||id('ingredient'),quantity:Number(x.quantity),order:x.order??i}));if(body.steps)next.steps=body.steps.map((x,i)=>({...current.steps[i],...x,id:current.steps[i]?.id||x.id||id('step'),order:x.order??i,timerSeconds:x.timerSeconds?Number(x.timerSeconds):null}));db.recipes[idx]=next;save(db);return{success:true,recipe:clone(recipeWithMedia(db,next))}},
  deleteRecipe:async(rid)=>{const db=load();const count=db.sessions.filter(s=>s.recipeId===rid).length;if(count)throw new Error(`This recipe has ${count} bake${count===1?'':'s'} in your Journal. Deleting it would delete that history too — not allowed.`);db.recipes=db.recipes.filter(r=>r.id!==rid);save(db);return{success:true,message:'Recipe deleted'}},
  startSession:async(recipeId)=>{const db=load();const recipe=db.recipes.find(r=>r.id===recipeId);if(!recipe)throw new Error('Recipe not found');if(!recipe.steps.length)throw new Error('This recipe has no steps yet — add a Method before starting a Bake.');const s={id:id('session'),recipeId,bakeNumber:db.sessions.filter(x=>x.recipeId===recipeId).length+1,status:'in_progress',currentStepOrder:recipe.steps[0].order,finalPhotoId:null,finalNotes:null,rating:null,whatToChangeNextTime:null,startedAt:now(),completedAt:null,updatedAt:now(),steps:recipe.steps.map(rs=>({id:id('sessionstep'),recipeStepId:rs.id,completed:false,notes:null,completedAt:null,photoIds:[]}))};db.sessions.push(s);save(db);return{success:true,session:clone(sessionFull(db,s))}},
  getSession:async(sid)=>{const db=load();const s=sessionFull(db,db.sessions.find(x=>x.id===sid));if(!s)throw new Error('Bake session not found');return{success:true,session:clone(s)}},
  getContinuableSession:async()=>{const db=load();const s=[...db.sessions].filter(x=>x.status==='in_progress').sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt)))[0];return{success:true,session:s?clone(sessionFull(db,s)):null}},
  updateSessionProgress:async(sid,body)=>{const db=load();const s=db.sessions.find(x=>x.id===sid);if(!s)throw new Error('Bake session not found');if(s.status!=='in_progress')throw new Error(`This bake is already ${s.status} — progress can't be changed.`);if(body.currentStepOrder!==undefined)s.currentStepOrder=Number(body.currentStepOrder);for(const u of body.stepUpdates||[]){const st=s.steps.find(x=>x.id===u.sessionStepId);if(!st)continue;if(u.completed!==undefined){st.completed=Boolean(u.completed);st.completedAt=u.completed?now():null}if(u.notes!==undefined)st.notes=u.notes}s.updatedAt=now();save(db);return{success:true,session:clone(sessionFull(db,s))}},
  attachStepPhoto:async(sid,body)=>{const db=load();const s=db.sessions.find(x=>x.id===sid);const st=s?.steps.find(x=>x.id===body.sessionStepId);if(!st)throw new Error('Bake session not found');st.photoIds=[...(st.photoIds||[]),body.mediaAssetId];s.updatedAt=now();save(db);return{success:true,session:clone(sessionFull(db,s))}},
  completeSession:async(sid,body)=>{const db=load();const s=db.sessions.find(x=>x.id===sid);if(!s)throw new Error('Bake session not found');s.status='completed';s.completedAt=now();s.updatedAt=now();s.finalPhotoId=body.finalPhotoId||null;s.finalNotes=body.finalNotes||null;s.rating=body.rating?Number(body.rating):null;s.whatToChangeNextTime=body.whatToChangeNextTime||null;save(db);return{success:true,session:clone(sessionFull(db,s))}},
  abandonSession:async(sid)=>{const db=load();const s=db.sessions.find(x=>x.id===sid);if(!s)throw new Error('Bake session not found');s.status='abandoned';s.updatedAt=now();save(db);return{success:true,session:clone(sessionFull(db,s))}},
  getJournal:async()=>{const db=load();const sessions=db.sessions.filter(s=>['completed','abandoned'].includes(s.status)).sort((a,b)=>String(b.completedAt||b.updatedAt).localeCompare(String(a.completedAt||a.updatedAt))).map(s=>sessionFull(db,s));return{success:true,count:sessions.length,sessions:clone(sessions)}},
  getJournalEntry:async(sid)=>offline.getSession(sid), getRecipeBakes:async(rid)=>{const db=load();const sessions=db.sessions.filter(s=>s.recipeId===rid).sort((a,b)=>b.bakeNumber-a.bakeNumber);return{success:true,count:sessions.length,sessions:clone(sessions)}},
  getGroceryItems:async()=>{const items=[...load().groceries].sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));return{success:true,count:items.length,items:clone(items)}}, addGroceryItem:async(body)=>{const db=load();const item={id:id('grocery'),label:body.label,quantity:body.quantity||null,checked:false,sourceRecipeId:body.sourceRecipeId||null,createdAt:now()};db.groceries.push(item);save(db);return{success:true,item:clone(item)}}, addGroceriesFromRecipe:async(rid)=>{const db=load();const r=db.recipes.find(x=>x.id===rid);if(!r)throw new Error('Recipe not found');const items=r.ingredients.map(i=>({id:id('grocery'),label:i.name,quantity:`${i.quantity} ${i.unit}`,checked:false,sourceRecipeId:rid,createdAt:now()}));db.groceries.push(...items);save(db);return{success:true,count:items.length,items:clone(items)}}, updateGroceryItem:async(gid,body)=>{const db=load();const item=db.groceries.find(x=>x.id===gid);if(!item)throw new Error('Grocery item not found');Object.assign(item,body);save(db);return{success:true,item:clone(item)}}, deleteGroceryItem:async(gid)=>{const db=load();db.groceries=db.groceries.filter(x=>x.id!==gid);save(db);return{success:true}},
  uploadMedia:async(file)=>{const db=load();const dataUrl=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file)});const media={id:id('media'),url:dataUrl,publicId:null,width:null,height:null,bytes:file.size,createdAt:now()};db.media.push(media);save(db);return{success:true,media:clone(media)}},
  getRecipeNutrition:async()=>({success:true,nutrition:null,message:'Nutrition lookup requires an internet connection in this offline edition.'}), rematchIngredient:async()=>{throw new Error('Nutrition rematching requires an internet connection.')},
  reset:()=>{localStorage.removeItem(KEY)}
};
